export enum RepositoryEnum  {
    PRODUCT_REPOSITORY = "PROCUCT_REPOSITORY",
    CATEGORY_REPOSITORY = " CATEGORY_REPOSITORY",
    CANCION_REPOSITORY = " CANCION_REPOSITORY",
    CANTANTE_REPOSITORY = " CANTANTE_REPOSITORY",
}