export * from "./cantante/base-cantante.dto"
export * from "./cantante/create-cantante.dto"
export * from "./cantante/pagination-cantante.dto"
export * from "./cantante/read-cantante.dto"
export * from "./cantante/update-cantante.dto"